### ISSUE TITLE
Does the package have a dependency on VS 2015?

### ISSUE THREAD

**Issue by The-Futurist** [deadlydog/New-NuGetPackage#13]
Can anyone confirm whether or not this package itself requires the presence of VS 2015? Developers working here have VS 2017 and VS 2015 installed on their machines and when they build everything's OK.

But we are exploring VSTS and when it runs a build agent on a machine that does NOT have VS 2015 it seems to fail, someone told me that it looks like VS 2015 must be installed and we're good, but is that true?

The file New-NuGetPackage.ps1 contains this line you see:

`	$vsCommonToolsPaths = @($env:VS140COMNTOOLS,$env:VS120COMNTOOLS,$env:VS110COMNTOOLS,$env:VS100COMNTOOLS)
`

And VS140 presumably refers to VS 2015?

**Comment by deadlydog** [comment]
I use it on local and build machines that have only Visual Studio 2017 installed and don't have any problems. That bit of code that you referenced though is for locating the `TF.exe` in order to checkout files when using TFVC (Team Foundation Version Control). All of my projects are using Git now, which would explain why I don't see the issue. I'm assuming you guys are using TFVC?

With VS 2017 Microsoft stopped adding the VS1X0COMNTOOLS environment variable, which is why we can't easily just go add `$env:VS150COMNTOOLS` to that line (because `$env:VS150COMNTOOLS` doesn't exist). I'll see if I can get the code updated to locate TF.exe when using VS 2017, and probably an optional script parameter to allow you to specify the path explicitly if wanted.

**Comment by deadlydog** [comment]
Hey @Korporal I implemented the new functionality and published it in the new v1.5.10 of the New-NuGetPackage.ps1 script and v1.8.15 version of NuGet package. Give that a try and see if it gets things working for you again and let me know. Thanks.

**Comment by deadlydog** [comment]
No response so closing this item. If it's still an issue feel free to reopen this.
