### ISSUE TITLE
Using with VSTS

### ISSUE THREAD

**Issue by pallu** [deadlydog/New-NuGetPackage#4]
How should I set up config.ps1 to push to a VSTS package feed? As per the VSTS documentation on [https://www.visualstudio.com/en-us/docs/package/nuget/nuget-exe#add-a-feed-to-nuget-2](url) this is what should go:
`nuget.exe push -Source "https://mysite.pkgs.visualstudio.com/_packaging/<FeedName>/nuget/v3/index.json" -ApiKey VSTS my_package.nupkg`
There is a VSTS Credential Provider (`CredentialProvider.VSS.exe`) that has to be in the same path as `nuget.exe` and when it is run, it asks for the credentials. When I run the command as provided in the documentation, it works fine, however even after copying `CredentialProvider.VSS.exe` to the `DoNotModify` folder and running the `.cmd` file, the credential screen never pops up, the script runs without any error, but nothing gets pushed. Any way to push it to the VSTS feed?

Thanks

**Comment by deadlydog** [comment]
I haven't published to a VSTS package feed before, but I wouldn't expect it to be any different than any other custom nuget package feed. Have you seen [the documentation](https://github.com/deadlydog/New-NuGetPackage/blob/master/docs/NuGetPackageToCreateANuGetPackageFromYourProjectAfterEveryBuild.md#pushing-to-a-custom-nuget-gallery) showing what you need to modify in the `config.ps1` file in order to publish to a custom nuget package feed?

I think you should just need:
```
$sourceToUploadTo = "https://mysite.pkgs.visualstudio.com/_packaging/<FeedName>/nuget/v3/index.json"

$apiKey = "VSTS"
```

Although looking at that now, I see what you mean about the credentials provider. So I would still try using the above config and dropping the CredentialProvider.VSS.exe in the `DoNotModify` directory beside the `NuGet.exe`. I wonder if there's a way to upload to those feeds just by using a regular API key? Or is using the CredentialsProvider a hard requirement?

Also, I just published a new version of the NuGet package a couple days ago that switches from using NuGet.exe v3.5.0 to 4.3.0, so perhaps using the newest version might get things working for you as well.

**Comment by pallu** [comment]
I _did_ try the above recommendations. I copied the `CredentialProvider.VSS.exe in` that folder and changed the` config.ps1`, however it didn't work, neither did upgrading NuGet.exe. I guess I'll now have to allow VSTS to compile it and deploy it internally.

**Comment by deadlydog** [comment]
Hey @pallu, are you able to get it to work without using my NuGet package and just manually using NuGet.exe? My NuGet package is just a simple wrapper / pass-thru to NuGet.exe, so if you can get it to work manually by using NuGet.exe from the command line, we should be able to get it to work with the NuGet package. If you decide to try using the NuGet.exe manually from the command line, let me know if you get it to work, and what you needed to do to get it to work. Thanks.

**Comment by pallu** [comment]
Yes, it works with manual NuGet.
  
  
  

  
  
  
  
  
>

**Comment by deadlydog** [comment]
Can you give me the command you are using to publish when you do it manually and it works please?

**Comment by pallu** [comment]
So from my original question, this is what I use:
`nuget.exe push -Source "https://mysite.pkgs.visualstudio.com/_packaging/<FeedName>/nuget/v3/index.json" -ApiKey VSTS my_package.nupkg`
It pops up a Microsoft Login dialog box. After I enter my credentials, it pushes it to the VSTS Package Repository.

**Comment by deadlydog** [comment]
Oh, ugh, sorry about that. I totally forgot you had already given it to me.

Would you be able to provide me the output of the New-NuGetPackage.ps1 script, when you call it with the `-Verbose` flag please.
