### ISSUE TITLE
Different operation when used with .Net Standard 2 class library projects

### ISSUE THREAD

**Issue by JonPaz** [deadlydog/New-NuGetPackage#9]
Firstly, thanks for a really useful tool - made life much easier.

I'm moving projects across to Standard 2.0 and noticed that the addition of the CreateNewNuGetPackageFromProjectAfterEachBuild package gives different results than for Framework 4.6 projects.  As shown below, when added to the (top) Standard project (VS2017 15.5.2) the _CreateNewNugetPackage folder and associated scripts etc. is not created and building the project does create a Nuget package.

Any thoughts on this?

Thanks in advance!

![image](https://user-images.githubusercontent.com/6118046/35707234-dfe45bf8-07a0-11e8-9006-01bc131cb4ef.png)

**Comment by deadlydog** [comment]
.Net Core no longer supports having PowerShell scripts run when the NuGet package is installed and uninstalled, and thus it can't add the pre-build event to the project file to have it create the nuget package on each build. Because of this, I don't think it will be possible for me to port this NuGet package to work with .Net Core/Standard projects.

Don't fret though, because .Net Core projects (I'm not sure about .Net Standard) now support creating NuGet packages natively, so you shouldn't even require my NuGet package anymore. I haven't actually created a .Net Core/Standard project myself yet though to try this out, so I don't know if it will have feature parity with what my NuGet package provides.

I believe you can configure the .Net Core project to create a NuGet package in one of the tabs within the project properties.  Hopefully that gives you enough info to get you going; and Google can probably fill in any gaps.

**Comment by Kjartanl** [comment]
Hi @JonPaz. 

I'm currently working in a VS Solution where I've got one project for which I'm using this NuGet package, and several other projects that are written in .Net Core. For these latter, I too tried to use *New-NuGetPackage* before realizing that packaging is built-in now. 

What you need to do is open the **Properties** view for a project and select the **Package tab.** Here, you can check "*Generage NuGet package on build*" at the top if you like - that will generate a package either in your `bin/debug/` or `bin/release` folder (depending on your configuration) after each build. 

If you don't want that, you can generate the equivalent package in the same folder by **right-clicking the project node and selecting pack** from the context menu. 

As for configuring your package, it should be immediately clear how to do this once you open the view mentioned above (properties > Package).

**Comment by deadlydog** [comment]
Thanks for responding @Kjartanl 👍 

The one thing that I don't think is built-in to the .Net Core projects is publishing the generated .nupkg file (please correct me if I'm wrong). However, you can still use the New-NuGetPackage.ps1 script (rather than the VS NuGet package) to perform the upload.
